profile/Models/Crypto.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Builder;

namespace profile.Models
{

    public class RootObject
    {
        public Status status { get; set; }
        public List<Datum> data { get; set; }
    }

    [Table("crypto")]
    public class Crypto
    {
        [Required]
        [Key]
        public int userid { get; set; }
        public string idtoken { get; set; }

        [Required(ErrorMessage = "Username must be "), StringLength(40), Display(Name = "Username")]
        public string username { get; set; }
        public string password { get; set; }
        //public virtual ICollection<Crypto> portfolio { get; set; }
        // public IAsyncEnumerable<Crypto> watchlist { get; set; }

    }

    [Table("status")]
    public class Status
    {
        [Required]
        [Key]
        public int statusid { get; set; }
        public DateTime timestamp { get; set; }
        public int error_code { get; set; }
        public string error_message { get; set; } //object
        public int elapsed { get; set; }
        public int credit_count { get; set; }
    }

    // You may need to install the Microsoft.AspNetCore.Http.Abstractions package into your project
    [Table("datum")]
    public class Datum
    {
        [Required]
        [Key]
        public int datumid { get; set; }
        public int id { get; set; }
        public string name { get; set; }
        public string symbol { get; set; }
        public string slug { get; set; }
        public int num_market_pairs { get; set; }
        public DateTime date_added { get; set; }
        //public List<object> tags { get; set; } list not supp, foreign key
        public double? max_supply { get; set; }
        public double? circulating_supply { get; set; }
        public double? total_supply { get; set; }
        //public Platform platform { get; set; }
        public int cmc_rank { get; set; }
        public DateTime last_updated { get; set; }
        public virtual Quote quote { get; set; }
    }


    [Table("usd")]
    public class Usd
    {
        [Required]
        [Key]
        public int usdid { get; set; }
        public Int64? price { get; set; }
        public Int64? volume_24h { get; set; }
        public Int64? percent_change_1h { get; set; }
        public Int64? percent_change_24h { get; set; }
        public Int64? percent_change_7d { get; set; }
        public Int64? market_cap { get; set; }
        public DateTime last_updated { get; set; }

    }

    [Table("quote")]
    public class Quote
    {
        [Required]
        [Key, ForeignKey("usdid")]
        public int quoteid { get; set; }
        public Usd USD { get; set; }

        //  [ForeignKey("usdid")]
        //  public int usdid { get; set; }
    }

    // Extension method used to add the middleware to the HTTP request pipeline.
    public static class CryptoExtensions
    {
        public static IApplicationBuilder UseMiddlewareClassTemplate(this IApplicationBuilder builder)
        {
            return builder.UseMiddleware<Crypto>();
        }
    }
}

profile/Controllers/CryptoController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using profile.Models;
using System.Net.Http;
using System.IO;
using System.Text;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace profile.Controllers
{
    public class CryptoController : Controller
    {

        public async Task<IActionResult> Index()
        {
            var client = new HttpClient();

            // Create the HttpContent for the form to be posted.
            var requestContent = new FormUrlEncodedContent(new[] {
            new KeyValuePair<string, string>("text", "This is a block of text"),
            });

            // Get the response.
            HttpResponseMessage response = await client.PostAsync(
                "https://api.blockcypher.com/v1/bcy/test/oap/addrs?token=a94aab1313a9471a97779a8b6facac80",
                requestContent);

            // Get the response content.
            HttpContent responseContent = response.Content;

            // Get the stream of the content.
            using (var reader = new StreamReader(await responseContent.ReadAsStreamAsync()))
            {
                // Write the output.
                var test1 = await reader.ReadToEndAsync();
                Console.WriteLine(test1);
                var reservation = JsonConvert.DeserializeObject<CreateWallet>(test1);

                //return View(Json(reader.ReadToEndAsync()));
              return View(reservation);
            }            // Pass the data into the View
        }

        //public ViewResult Index()
        //{
        //    return View(Wallet());
        //}

    }
}

profile/Views/Crypto/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@*@using Newtonsoft.Json;
@using Newtonsoft.Json.Linq;
@using Microsoft.AspNetCore.Http*@
@{

    @*string content = ...; // String containing the json data.
    var json = JObject.Parse(content);*@

}


@model profile.Models.CreateWallet



<br>
<br>
<div class="container">
    <h1>BTC Wallet Details</h1>
    <hr />

    <form asp-controller="Crypto" asp-action="Index" method="get" />
    <div class="form-group">
        <input type="hidden" name="public" class="form-control" required />
        <fieldset>
            <div class="form-group">
                <label>Wallet address</label>
                @Html.DisplayFor(modelItem => modelItem.original_address)
                @*<p>@Model.original_address.ToString()</p><br>*@
                @*@Html.Raw(JsonConvert.SerializeObject(Student.CreateEmpty(), Formatting.Indented))*@

            </div>

            <div class="form-group">
                <label>Public key</label>
                @Html.DisplayFor(modelItem => modelItem.@public)

            </div>

            <div class="form-group">
                <label>Public key</label>
                @Html.DisplayFor(modelItem => modelItem.@private)

            </div>

            @*<div class="form-group">
            <label for="text">Check a BTC wallet balance</label>
            <output class="form-control" type="text" name="shortdescription" asp-route-id="@Model.Value==public" data-length="5000" nameplaceholder="Short Description" required />
        </div>*@

        </fieldset>
    </div>
    @*<button type="submit" class="btn btn-primary">Add Post</button>*@
    <br /><br />

</div>